[project]
name = "repo2kernel"
version = "0.1.0"
description = "Turn repositories in various languages into environments suitable for a Jupyter kernel. Inspired by repo2docker."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter-repo2docker>=2025.8.0",
    "packaging>=25.0",
    "pyyaml>=6.0.2",
]


[project.scripts]
repo2kernel = "main.py:main"

[tool.uv.sources]
jupyter-repo2docker = { git = "https://github.com/jupyterhub/repo2docker", rev = "358888c6a93839dd4c60859737d886e49a4a1247" }
